# Generated by Django 3.0.4 on 2020-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/glovoapp/w_680,h_240,c_fit,f_auto,q_auto/Products/phfj7p3w7dhjpxzovqk6', upload_to=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
